### ISSUE TITLE
不能用。。。

### ISSUE THREAD

**Issue by ijustyce** [huiwang/hexo-baidu-url-submit#1]
按照您的博文，最后加入新的deployer：
`deploy:
- type: baidu_url_submitter
`
我在_config.ym文件里加入后都不能hexo g了，然后我改了你的index.js 
`hexo.extend.generator.register('baidu_url_generator', require('./lib/generator'));
hexo.extend.generator.register('baidu_url_submitter', require('./lib/submitter'));
`
好是好了，但是百度自动推送有条数限制，我不能每次hexo d都推送啊，您有更好的解决方案吗？

**Comment by huiwang** [comment]
你好 杨春，非常感谢你的反馈。

我目前的配置是每次只推送最新的一条博客。因为我每次只写一篇文章。

另外百度的上限是很高的，你遇到了错误提示了吗？

此外，我这里没有修改代码，也是可以用的，你能创建一个pullrequest吗，我排查一下。

谢谢。

**Comment by ijustyce** [comment]
百度的配置是很高的，但是推送有两个接口，一个是推送数据，一个是更新数据，更新的时候也调用推送数据接口我不确定百度会怎么处理，有什么影响，另外根目录下的_config.yml 应该如何配置？我的如下：
deploy:
  #type: git
  type: baidu_url_submitter
  # git 仓库的地址。
  repo: git@git.coding.net:ijustyce/blog.git
  # 分支名称。
  branch: master

同时有两个type 报错，同时有两个deploy也报错。我该如何写？新手，请多多指导哈。

**Comment by huiwang** [comment]
一下是我的配置文件，type之前有小横杠
```
deploy:
- type: baidu_url_submitter
- type: s3
  bucket: hui-wang.info
```

另外你之前说改代码了，我这的代码是不用改的，报的错误是什么？

**Comment by ijustyce** [comment]
配置好了，我需要配置成如下才可以，hexo我是新手，谢谢。
`
deploy:
- type: git
  repo: git@git.coding.net:ijustyce/blog.git
  branch: master
- type: baidu_url_submitter
`

**Comment by ijustyce** [comment]
我弄好了，我需要配置成：

`deploy:
- type: git
  repo: git@git.coding.net:ijustyce/blog.git
  branch: master
- type: baidu_url_submitter`
