### ISSUE TITLE
链接提交页面变了

### ISSUE THREAD

**Issue by MyronJi** [huiwang/hexo-baidu-url-submit#16]
百度站长工具貌似改版了？
链接提交好想和文中提到的不是一个东西了，作者能更新一下使用方法吗？

也有可能是我找错地方了？
https://ziyuan.baidu.com/

**Comment by huiwang** [comment]
多谢提醒，你有错误报告吗？

**Comment by MyronJi** [comment]
搞定了，要验证一样网站。

还有个问题。。linux不支持吗？我是ubuntu16.04
