### ISSUE TITLE
能否支持amp页面主动提交？

### ISSUE THREAD

**Issue by tiexo** [huiwang/hexo-baidu-url-submit#18]
百度支持提交amp页面了，我看了下主动推送接口差不多，多了一个&type=amp

**Comment by huiwang** [comment]
@tiexo  #17 这个有一个PR在加这个support，能解释一下这有什么用吗？

**Comment by tiexo** [comment]
@huiwang 
AMP即“Accelerated Mobile Pages Project（移动端网页加速加载技术）”的简称，是由谷歌及内容商共同发起的改善移动网页加速开源项目。

适配AMP页面后，移动端会优先加载，网站打开速度会变快。
而在百度提交会加快收录这种页面。
