### ISSUE TITLE
deploy设置问题

### ISSUE THREAD

**Issue by buptweixin** [huiwang/hexo-baidu-url-submit#2]
请问在_config.yml已经存在`type: git`的情况下，怎么添加`type:badu_url_comm`

**Comment by huiwang** [comment]
```
deploy:
- type: baidu_url_submitter
- type: s3
  bucket: hui-wang.info
```

**Comment by tauking** [comment]
> deploy:
>   type: baidu_url_submitter
>   type: git
>   repo: 
>     github: git@github.com:xxx/xxx.github.io.git,master
>     coding: git@git.coding.net:xxx/xxx.git,master

这么写后，报错：

> $ hexo clean
> FATAL duplicated mapping key at line 102, column 12:
>       type: git
>                ^
> YAMLException: duplicated mapping key at line 102, column 12:
>       type: git
>                ^
>     at generateError (D:\hexoBlog\git_hexo\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
>

**Comment by khs1994** [comment]
@tauking 


- type: baidu_url_submitter 

把前边的 type前的 横线  加上

**Comment by zdaiot** [comment]
你好，问下 bucket: hui-wang.info 这个设置有什么用？

**Comment by Hconly** [comment]
> @tauking
> 
> `- type: baidu_url_submitter `
> 
> 把type前的 横线 加上

-type
