### ISSUE TITLE
主动提交之后大概多少时间能在百度检索到自己的博客呢？

### ISSUE THREAD

**Issue by coderSkyChen** [huiwang/hexo-baidu-url-submit#4]
首先感谢您的贡献，使用了这个插件很方便地实现了主动提交。
我想问的是，主动提交之后，百度是不是需要一段时间才能对提交的网址建立索引呢？
主动提交了2天了，还是无法在百度检索到自己的博客呢~
谢谢~

**Comment by huiwang** [comment]
要查网站是否被收录，可以在百度里搜如下命令
`site: hui-wang.info`
把域名换作你博客的

**Comment by coderSkyChen** [comment]
@huiwang 好的，感谢~
